title: Alex Velia
author: Chikimuras
email: chikidevandcode@gmail.com
description: > # this means to ignore newlines until "baseurl:"
Bienvenue sur ma page, je m'entraine a faire des pullrequest et a créer une page github.

# social links
twitter_username: @Code42Dev
github_username:  Chikimuras

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
